src/objects/Case_Product__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>ProductCaseAssociation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>ProductCaseAssociation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>PCA-{00000}</displayFormat>
        <label>Case Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/ChartControllerHelperTest.cls
@isTest
public class ChartControllerHelperTest {
    private testmethod static void testCaseStatuses() {
        List<String> statuses = ChartControllerHelper.getCaseStatuses();
        System.assert(!statuses.isEmpty());
    }
    
    private testmethod static void testAddCaseStatsToProductCaseData() {
        Product2 prod = new Product2(Name = 'testProd', Price__c = 123);
        insert prod;
        
        List<Case_Product__c> productCases = [SELECT Case__c, Case__r.RecordType.DeveloperName
                                                  FROM Case_Product__c
                                                  WHERE Product__c = :prod.Id];
        
        ChartController.ProductCaseData pcd = new ChartController.ProductCaseData(prod, productCases);
        
        System.assert(pcd != null);
        ChartControllerHelper.addCaseStatsToProductCaseData(
            new List<ChartController.ProductCaseData>{pcd});
        
        System.assert(!pcd.caseStats.isEmpty());
    }
}